# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: FirstStage
  jobs:
  - template: templates/template.yml
    parameters:
      middleSteps:
      - script: echo "first stage"
      - script: echo "second script"

  - template: templates/template.yml
    parameters:
      test: 'okay'