parameters:
    middleSteps: []
    test: 'k'
    pool: 
      vmImage: 'ubuntu-latest'
    
    
jobs:

- job: Build
  displayName: Build
  
  dependsOn: ${{ parameters.dependsOn }}

  pool: ${{ parameters.pool }}
  steps: 

  - script: | 
      echo "what up world ${{ parameters.test }}"

  - ${{ parameters.middleSteps }}